# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 53306:3306
    volumes:
      - ./db-data:/var/lib/mysql
